using System;

namespace OdinInterop
{
    /// <summary>
    /// Marks a class whose methods should be exported from C# to Odin.
    /// Private/internal methods are exported as callable functions in Odin.
    /// </summary>
    public class OdinExportAttribute : Attribute
    {
        public OdinExportAttribute() { }

        public string odinSrcAppend { get; set; } = "";
    }

    /// <summary>
    /// Marks a class whose public static partial methods should be imported from Odin into C#.
    /// These are Odin functions exposed as C# callable methods.
    /// </summary>
    public class OdinImportAttribute : Attribute
    {
        public OdinImportAttribute() { }

        public string odinSrcAppend { get; set; } = "";
    }

    /// <summary>
    /// Declares the foreign (Odin) function that backs a C# import method.
    /// Carries the original Odin name, return type, and parameter types so the
    /// InteropGenerator can produce correct Odin wrapper code.
    /// Generated by Odin2Cs.
    /// </summary>
    [AttributeUsage(AttributeTargets.Method)]
    public class ForeignDeclAttribute : Attribute
    {
        /// <summary>The original Odin function name (e.g. "navmesh_create").</summary>
        public string OdinName { get; set; } = "";

        /// <summary>Original Odin return type (e.g. "int", "i64", "" for void).</summary>
        public string ReturnType { get; set; } = "";

        /// <summary>Original Odin parameter types, in order (e.g. ["int", "i64"]).</summary>
        public string[] ParamTypes { get; set; } = System.Array.Empty<string>();

        /// <summary>The Odin package where this function lives (e.g. "interop"). Used to emit the correct import and call prefix.</summary>
        public string OdinPackage { get; set; } = "";
    }
}
